In [ ]:
!cat examples/ex1.csv
a, b, c, d, message
1, 2, 3, 4, hello
5, 6, 7, 8, world
9, 10, 11, 12, foo

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../examples/ex1.csv")

In [8]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
pd.read_csv("../examples/ex2.csv", header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [10]:
pd.read_csv("../examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
names = ["a", "b", "c", "d", "message"]

In [12]:
pd.read_csv("../examples/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [13]:
parsed = pd.read_csv("../examples/csv_mindex.csv",
                     index_col=["key1", "key2"])

In [14]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [ ]:
result = pd.read_csv("../examples/ex3.txt", sep="\s+")

In [16]:
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [17]:
pd.read_csv("../examples/ex4.csv", skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [18]:
result = pd.read_csv("../examples/ex5.csv")

In [19]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [20]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [21]:
result = pd.read_csv("../examples/ex5.csv", na_values=["NULL"])

In [22]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [23]:
result2 = pd.read_csv("../examples/ex5.csv", keep_default_na=False)

In [24]:
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [25]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [26]:
result3 = pd.read_csv("../examples/ex5.csv", keep_default_na=False,
                      na_values=["NA"])

In [27]:
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [28]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [29]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}

In [30]:
pd.read_csv("../examples/ex5.csv", na_values=sentinels,
            keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

In [31]:
result = pd.read_csv("../examples/ex6.csv")

In [32]:
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [33]:
pd.read_csv("../examples/ex6.csv", nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [34]:
chunker = pd.read_csv("../examples/ex6.csv", chunksize=1000)

In [35]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [36]:
tot = pd.Series([], dtype="int64")
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)

In [37]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [38]:
data = pd.read_csv("../examples/ex5.csv")

In [39]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [40]:
data.to_csv("../examples/out.csv")

In [41]:
import sys

In [42]:
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [43]:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [44]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [45]:
import csv

In [46]:
f = open("../examples/ex7.csv")

In [47]:
reader = csv.reader(f)

In [48]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [49]:
f.close()

In [50]:
with open("../examples/ex7.csv") as f:
    lines = list(csv.reader(f))

In [51]:
header, values = lines[0], lines[1:]

In [52]:
data_dict = {h: v for h, v in zip(header, zip(*values))}

In [53]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [54]:
import csv

class my_dialect(csv.Dialect):
    lineterminator = "\n"
    delimiter = ";"
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

# Обязательно помещаем всё чтение ВНУТРЬ блока with
with open("../examples/ex7.csv") as f:
    reader = csv.reader(f, dialect=my_dialect)  # Исправили имя параметра (dialect)
    for line in reader:
        print(line)

['a,"b","c"']
['1,"2","3"']
['1,"2","3"']

In [55]:
with open("mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(("1", "2", "3"))
    writer.writerow(("4", "5", "6"))
    writer.writerow(("7", "8", "9"))

In [56]:
obj = """
{"name": "Wes",
"citied_lived": ["Akron", "Nashville", "New York", "San Francisco"],
"pet": null,
"siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
            {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

In [57]:
import json

In [58]:
result = json.loads(obj)

In [59]:
result

{'name': 'Wes',
 'citied_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [60]:
asjson = json.dumps(result)

In [61]:
asjson

'{"name": "Wes", "citied_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [62]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])

In [63]:
siblings

    name  age
0  Scott   34
1  Katie   42

In [64]:
data = pd.read_json("../examples/example.json")

In [65]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [66]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [67]:
data.to_json(sys.stdout, orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [ ]:
%pip install lxml

In [69]:
tables = pd.read_html("../examples/fdic_failed_bank_list.html")

In [70]:
len(tables)

1

In [71]:
failures = tables[0]

In [72]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [73]:
close_timestamps = pd.to_datetime(failures["Closing Date"])

In [74]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

In [75]:
from lxml import objectify

In [76]:
path = "../datasets/mta_perf/Performance_MNR.xml"

In [77]:
with open(path) as f:
    parsed = objectify.parse(f)

In [78]:
root = parsed.getroot()

In [79]:
data = []

skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
"DESIRED_CHANGE", "DECIMAL_PLACES"]
for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

In [80]:
perf = pd.DataFrame(data)

In [81]:
perf.head

<bound method NDFrame.head of               AGENCY_NAME                        INDICATOR_NAME  \
0    Metro-North Railroad  On-Time Performance (West of Hudson)
1    Metro-North Railroad  On-Time Performance (West of Hudson)
2    Metro-North Railroad  On-Time Performance (West of Hudson)
3    Metro-North Railroad  On-Time Performance (West of Hudson)
4    Metro-North Railroad  On-Time Performance (West of Hudson)
..                    ...                                   ...
643  Metro-North Railroad                Escalator Availability
644  Metro-North Railroad                Escalator Availability
645  Metro-North Railroad                Escalator Availability
646  Metro-North Railroad                Escalator Availability
647  Metro-North Railroad                Escalator Availability

                                           DESCRIPTION  PERIOD_YEAR  \
0    Percent of commuter trains that arrive at thei...         2008
1    Percent of commuter trains that arrive at thei...         2008
2    Percent of commuter trains that arrive at thei...         2008
3    Percent of commuter trains that arrive at thei...         2008
4    Percent of commuter trains that arrive at thei...         2008
..                                                 ...          ...
643  Percent of the time that escalators are operat...         2011
644  Percent of the time that escalators are operat...         2011
645  Percent of the time that escalators are operat...         2011
646  Percent of the time that escalators are operat...         2011
647  Percent of the time that escalators are operat...         2011

     PERIOD_MONTH            CATEGORY FREQUENCY INDICATOR_UNIT YTD_TARGET  \
0               1  Service Indicators         M              %       95.0
1               2  Service Indicators         M              %       95.0
2               3  Service Indicators         M              %       95.0
3               4  Service Indicators         M              %       95.0
4               5  Service Indicators         M              %       95.0
..            ...                 ...       ...            ...        ...
643             8  Service Indicators         M              %       97.0
644             9  Service Indicators         M              %       97.0
645            10  Service Indicators         M              %       97.0
646            11  Service Indicators         M              %       97.0
647            12  Service Indicators         M              %       97.0

    YTD_ACTUAL MONTHLY_TARGET MONTHLY_ACTUAL
0         96.9           95.0           96.9
1         96.0           95.0           95.0
2         96.3           95.0           96.9
3         96.8           95.0           98.3
4         96.6           95.0           95.8
..         ...            ...            ...
643                      97.0
644                      97.0
645                      97.0
646                      97.0
647                      97.0

[648 rows x 12 columns]>

In [82]:
perf2 = pd.read_xml(path)

In [83]:
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

In [84]:
frame = pd.read_csv("../examples/ex1.csv")

In [85]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [86]:
frame.to_pickle("../examples/frame_pickle")

In [87]:
pd.read_pickle("../examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (25.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [89]:
fec = pd.read_parquet("../datasets/fec/fec.parquet")

In [91]:
%pip install openpyxl xlrd

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlrd, et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [92]:
xlsx = pd.ExcelFile("../examples/ex1.xlsx")

In [93]:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [94]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [95]:
frame = pd.read_excel("../examples/ex1.xlsx", sheet_name="Sheet1")

In [96]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [97]:
writer = pd.ExcelWriter("../examples/ex2.xlsx")

In [99]:
frame.to_excel(writer, sheet_name="Sheet1")

In [102]:
writer.close()

In [103]:
frame.to_excel("../examples/ex2.xlsx")

In [ ]:
%pip install tables

In [105]:
frame = pd.DataFrame({"a": np.random.standard_normal(100)})

In [106]:
store = pd.HDFStore("../examples/mydata.h5")

In [107]:
store["obj1"] = frame

In [108]:
store["obj1_col"] = frame["a"]

In [109]:
store

<class 'pandas.HDFStore'>
File path: ../examples/mydata.h5

In [110]:
store["obj1"]

           a
0   0.818480
1  -0.727570
2   0.647307
3   0.131097
4  -0.024855
..       ...
95  1.501834
96 -0.998660
97  1.850688
98 -0.086926
99 -0.241326

[100 rows x 1 columns]

In [111]:
store.put("obj2", frame, format="table")

In [112]:
store.select("obj2", where=["index >= 10 and index <= 15"])

           a
10  0.955758
11 -1.691081
12 -0.176307
13  0.785479
14 -0.159621
15 -1.822866

In [113]:
store.close()

In [115]:
frame.to_hdf("../examples/mydata.h5", key="obj3", format="table")

In [116]:
pd.read_hdf("../examples/mydata.h5", key="obj3", where=["index < 5"])

          a
0  0.818480
1 -0.727570
2  0.647307
3  0.131097
4 -0.024855

In [117]:
import os

In [118]:
os.remove("../examples/mydata.h5")

In [ ]:
%pip install requests

In [120]:
import requests

In [121]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [122]:
resp = requests.get(url)

In [123]:
resp.raise_for_status

In [124]:
resp

In [125]:
data = resp.json()

In [126]:
data[0]["title"]

'BUG: validate errors keyword in to_datetime (GH#66542)'

In [127]:
issues = pd.DataFrame(data, columns=["number", "title",
                                     "labels", "state"])

In [128]:
issues

,number,title,labels,state
0,66543,BUG: validate errors keyword in to_datetime (G...,[],open
1,66542,BUG: to_datetime raises bare AssertionError fo...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
2,66541,BUG: online ewm ignoring decay for single-colu...,[],open
3,66540,BUG: MultiIndex.isin raising TypeError on iter...,[],open
4,66539,TST: cover divmod/rdivmod on NA (GH#66493),[],open
5,66538,DOC: fix tutorial data card text in dark mode,[],open
6,66537,GH#50127,[],open
7,66536,BUG: Fix boolean column indexer for single-col...,[],open
8,66535,BUG: Timestamp constructor silently ignoring a...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,66534,BUG: loc/iloc setitem with boolean column inde...,[],open
10,66533,BUG: Timestamp ignored the nanosecond keyword ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
11,66531,BUG: pivot with array-like index/columns label...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
12,66530,BUG: IntervalArray/IntervalIndex only validate...,[],open
13,66529,BUG: tz-aware series with NaT raises exception...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
14,66527,BUG: DataFrame.loc assignment with boolean col...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
15,66526,DOC: Improve pull request guideline wording,[],open
16,66525,BUG: read_csv c engine collapses distinct fiel...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,66524,BUG: read_csv c engine silently truncates inte...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,66523,BUG/API: ewm with equally spaced times disagre...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,66522,BUG: DataFrame.ewm(...).online().mean() ignore...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
20,66521,BUG: ewm(adjust=False) wrong result with com=1...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
21,66518,BUG: IntervalArray silently builds interval[in...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
22,66517,BUG: convert_dtypes raises OverflowError for i...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
23,66516,BUG: Timestamp.replace producing a value equal...,[],open
24,66514,BUG: object of type 'list_iterator' has no len(),"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,66513,BUG: read_csv c engine matched na_values only ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,66512,"BUG: length-aware string hashtable keys, fixin...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,66511,"BUG: read_csv c engine truncated fixed-width, ...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,66508,BUG: object and extension-dtype reductions hon...,[],open
29,66504,BUG: Fix misleading ValueError in str.match wi...,[],open

In [129]:
import sqlite3

In [148]:
con.execute("DROP TABLE IF EXISTS test")

In [149]:
query = """
        CREATE TABLE IF NOT EXISTS test
        (a VARCHAR(20), b VARCHAR(20),
        c REAL, d INTEGER
        );"""

In [150]:
con = sqlite3.connect("mydata.sqlite")

In [151]:
con.execute(query)

In [152]:
data = [("Atlanta", "Georgia", 1.25, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]

In [153]:
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [154]:
con.executemany(stmt, data)

In [155]:
con.commit()

In [156]:
cursor = con.execute("SELECT * FROM test")

In [157]:
rows = cursor.fetchall()

In [158]:
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [159]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [160]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [ ]:
%pip install sqlalchemy

In [162]:
import sqlalchemy as sqla

In [163]:
db = sqla.create_engine("sqlite:///mydata.sqlite")

In [164]:
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5