In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]
})

In [3]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [4]:
data.columns

Index(['x0', 'x1', 'y'], dtype='str')

In [6]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [7]:
df2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])

In [8]:
df2

   one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [9]:
df3 = data.copy()

In [10]:
df3['string'] = ['a', 'b', 'c', 'd', 'e']

In [11]:
df3

   x0    x1    y string
0   1  0.01 -1.5      a
1   2 -0.01  0.0      b
2   3  0.25  3.6      c
3   4 -4.10  1.3      d
4   5  0.00 -2.0      e

In [12]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [13]:
model_cols = ['x0', 'x1']

In [14]:
data.loc[:, model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [17]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                   categories=['a', 'b'])

In [18]:
data

   x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [19]:
dummies = pd.get_dummies(data.category, prefix='category')

In [20]:
data_with_dummies = data.drop('category', axis=1).join(dummies)

In [21]:
data_with_dummies

   x0    x1    y  category_a  category_b
0   1  0.01 -1.5        True       False
1   2 -0.01  0.0       False        True
2   3  0.25  3.6        True       False
3   4 -4.10  1.3        True       False
4   5  0.00 -2.0       False        True

In [22]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]
})

In [23]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [24]:
%pip install -q patsy
import patsy

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [26]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [27]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [28]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [29]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [30]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [31]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

In [32]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [33]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)

In [34]:
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [35]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

In [36]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [37]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

In [38]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [39]:
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'y': [1, 2, 3, 4]
})

In [40]:
new_X = patsy.build_design_matrices([X.design_info], new_data)

In [41]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [42]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)

In [43]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [44]:
data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1': [1, 2, 3, 4, 5, 6, 7, 8],
    'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})

In [46]:
y, X = patsy.dmatrices('v2 ~ key1', data)

In [47]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [48]:
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)

In [49]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [50]:
y, X = patsy.dmatrices('v2 ~ C(key2)', data)

In [51]:
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [52]:
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})

In [53]:
data

  key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [54]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)

In [55]:
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [56]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)

In [57]:
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [58]:
%pip install -q statsmodels

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [59]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [64]:
# Для вопроизводимости результатов
rng = np.random.default_rng(seed=12345)

def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size
    return mean + np.sqrt(variance) * rng.standard_normal(size)

N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.1, size=N)
    ]
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

In [65]:
X[:5]

array([[-0.90050602, -0.18942958, -0.72681399],
       [ 0.79925205, -1.54598388, -0.2315047 ],
       [-0.55065483, -0.12025429,  0.23289198],
       [-0.16391555,  0.82403985,  0.14727256],
       [-0.04765129, -0.21314698, -0.0341134 ]])

In [66]:
y[:5]

array([-0.44899857, -0.54050826,  0.13740035, -0.03797771, -0.00830934])

In [67]:
X_model = sm.add_constant(X)

In [68]:
X_model[:5]

array([[ 1.        , -0.90050602, -0.18942958, -0.72681399],
       [ 1.        ,  0.79925205, -1.54598388, -0.2315047 ],
       [ 1.        , -0.55065483, -0.12025429,  0.23289198],
       [ 1.        , -0.16391555,  0.82403985,  0.14727256],
       [ 1.        , -0.04765129, -0.21314698, -0.0341134 ]])

In [69]:
model = sm.OLS(y, X)

In [70]:
results = model.fit()

In [71]:
results.params

array([0.06681503, 0.26803235, 0.43002923])

In [72]:
print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.387
Model:                            OLS   Adj. R-squared (uncentered):              0.368
Method:                 Least Squares   F-statistic:                              20.39
Date:                Sun, 23 Aug 2026   Prob (F-statistic):                    2.52e-10
Time:                        16:51:59   Log-Likelihood:                         -25.611
No. Observations:                 100   AIC:                                      57.22
Df Residuals:                      97   BIC:                                      65.04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0668      0.054      1.243      0.217      -0.040       0.174
x2             0.2680      0.042      6.313      0.000       0.184       0.352
x3             0.4300      0.096      4.458      0.000       0.239       0.621
==============================================================================
Omnibus:                        0.435   Durbin-Watson:                   1.869
Prob(Omnibus):                  0.805   Jarque-Bera (JB):                0.301
Skew:                           0.134   Prob(JB):                        0.860
Kurtosis:                       2.995   Cond. No.                         2.31
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [73]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])

In [74]:
data['y'] = y

In [75]:
data[:5]

       col0      col1      col2         y
0 -0.900506 -0.189430 -0.726814 -0.448999
1  0.799252 -1.545984 -0.231505 -0.540508
2 -0.550655 -0.120254  0.232892  0.137400
3 -0.163916  0.824040  0.147273 -0.037978
4 -0.047651 -0.213147 -0.034113 -0.008309

In [76]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()

In [77]:
results.params

Intercept   -0.020799
col0         0.065813
col1         0.268970
col2         0.428468
dtype: float64

In [78]:
results.tvalues

Intercept   -0.652501
col0         1.219768
col1         6.312369
col2         4.427381
dtype: float64

In [79]:
results.predict(data[:5])

0   -0.442431
1   -0.483214
2    0.010403
3    0.253157
4   -0.095882
dtype: float64

In [80]:
init_x = 4

values = [init_x, init_x]
N = 1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [81]:
from statsmodels.tsa.ar_model import AutoReg

In [82]:
MAXLAGS = 5

In [83]:
model = AutoReg(values, MAXLAGS)

In [85]:
results = model.fit()

In [86]:
results.params

array([ 0.02346612,  0.8096828 , -0.42865278, -0.03336517,  0.04267874,
       -0.05671529])

In [87]:
%pip install -q scikit-learn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [93]:
train = pd.read_csv('../datasets/titanic/train.csv')

In [94]:
test = pd.read_csv('../datasets/titanic/test.csv')

In [95]:
train[:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [96]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [97]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [99]:
impute_value = train['Age'].median()

In [100]:
train['Age'] = train['Age'].fillna(impute_value)

In [101]:
test['Age'] = test['Age'].fillna(impute_value)

In [102]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)

In [103]:
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [104]:
predictors = ['Pclass', 'IsFemale', 'Age']

In [105]:
X_train = train[predictors].to_numpy()

In [106]:
X_test = test[predictors].to_numpy()

In [107]:
y_train = train['Survived'].to_numpy()

In [108]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [109]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [110]:
from sklearn.linear_model import LogisticRegression

In [111]:
model = LogisticRegression()

In [112]:
model.fit(X_train, y_train)

LogisticRegression()

In [113]:
y_predict = model.predict(X_test)

In [114]:
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [115]:
from  sklearn.linear_model import LogisticRegressionCV

In [116]:
model_cv = LogisticRegressionCV(Cs=10)

In [ ]:
model_cv.fit(X_train, y_train)

In [120]:
from sklearn.model_selection import cross_val_score

In [121]:
model = LogisticRegression(C=10)

In [122]:
scores = cross_val_score(model, X_train, y_train, cv=4)

In [123]:
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])

In [ ]:
ss