In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'key1' : ['a', 'a', None, 'b', 'b', 'a', None],
                   'key2' : pd.Series([1, 2, 1, 2, 1, None, 1], dtype='Int64'),
                    'data1' : np.random.standard_normal(7),
                    'data2' : np.random.standard_normal(7)})

In [3]:
df

  key1  key2     data1     data2
0    a     1  0.953980 -0.966058
1    a     2  1.369504  0.647200
2  NaN     1 -0.789297  0.480744
3    b     2  1.160445 -1.726905
4    b     1  0.024336  0.495262
5    a  <NA>  1.606693 -0.409158
6  NaN     1  0.022242 -0.186802

In [4]:
grouped = df['data1'].groupby(df['key1'])

In [5]:
grouped

In [6]:
grouped.mean()

key1
a    1.310059
b    0.592390
Name: data1, dtype: float64

In [7]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()

In [8]:
means

key1  key2
a     1       0.953980
      2       1.369504
b     1       0.024336
      2       1.160445
Name: data1, dtype: float64

In [9]:
means.unstack()

key2         1         2
key1
a     0.953980  1.369504
b     0.024336  1.160445

In [10]:
states = np.array(['OH', 'CA', 'CA', 'OH', 'OH', 'CA', 'OH'])

In [11]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [12]:
df['data1'].groupby([states, years]).mean()

CA  2005    1.488099
    2006   -0.789297
OH  2005    1.057213
    2006    0.023289
Name: data1, dtype: float64

In [13]:
df.groupby('key1').mean()

      key2     data1     data2
key1
a      1.5  1.310059 -0.242672
b      1.5  0.592390 -0.615822

In [14]:
df.groupby('key2').mean(numeric_only=True)

         data1     data2
key2
1     0.052815 -0.044214
2     1.264975 -0.539852

In [15]:
df.groupby(['key1', 'key2']).mean()

              data1     data2
key1 key2
a    1     0.953980 -0.966058
     2     1.369504  0.647200
b    1     0.024336  0.495262
     2     1.160445 -1.726905

In [16]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [17]:
df.groupby('key1', dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [18]:
df.groupby(['key1', 'key2'], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [19]:
df.groupby('key1').count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [20]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  0.953980 -0.966058
1    a     2  1.369504  0.647200
5    a  <NA>  1.606693 -0.409158
b
  key1  key2     data1     data2
3    b     2  1.160445 -1.726905
4    b     1  0.024336  0.495262

In [21]:
for (k1, k2), group in df.groupby(['key1', 'key2']):
    print((k1, k2))
    print(group)

('a', 1)
  key1  key2    data1     data2
0    a     1  0.95398 -0.966058
('a', 2)
  key1  key2     data1   data2
1    a     2  1.369504  0.6472
('b', 1)
  key1  key2     data1     data2
4    b     1  0.024336  0.495262
('b', 2)
  key1  key2     data1     data2
3    b     2  1.160445 -1.726905

In [22]:
pieces = {name: group for name, group in df.groupby('key1')}

In [23]:
pieces['b']

  key1  key2     data1     data2
3    b     2  1.160445 -1.726905
4    b     1  0.024336  0.495262

In [24]:
mapping = {'key1': 'key', 'key2': 'key',
           'data1': 'data', 'data2': 'data'}

grouped = df.T.groupby(mapping)

In [25]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values.T)

data
      data1     data2
0   0.95398 -0.966058
1  1.369504    0.6472
2 -0.789297  0.480744
3  1.160445 -1.726905
4  0.024336  0.495262
5  1.606693 -0.409158
6  0.022242 -0.186802
key
  key1  key2
0    a     1
1    a     2
2  NaN     1
3    b     2
4    b     1
5    a  <NA>
6  NaN     1

In [26]:
df.groupby(['key1',  'key2'])[['data2']].mean()

              data2
key1 key2
a    1    -0.966058
     2     0.647200
b    1     0.495262
     2    -1.726905

In [27]:
s_grouped = df.groupby(['key1','key2'])['data2']

In [28]:
s_grouped

In [29]:
s_grouped.mean()

key1  key2
a     1      -0.966058
      2       0.647200
b     1       0.495262
      2      -1.726905
Name: data2, dtype: float64

In [30]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wanda', 'Jill', 'Trey'])

In [31]:
people.iloc[2:3, [1, 2]] = np.nan

In [32]:
people

              a         b         c         d         e
Joe   -1.472425  1.119081  0.771044  0.910171  1.451980
Steve -1.065126 -1.031149 -1.344409  0.752541  0.937667
Wanda  0.779662       NaN       NaN  0.408622  0.318786
Jill   1.558424 -1.266772 -0.676374  1.015421  0.338627
Trey  -0.161011 -0.117456 -1.109067 -0.101516  0.192271

In [33]:
mapping = {'a': 'red', 'b': 'red', 'c': 'blue',
           'd': 'blue', 'e': 'red', 'f': 'orange'}

In [37]:
by_column = people.T.groupby(mapping)

In [38]:
by_column.sum().T

           blue       red
Joe    1.681215  1.098636
Steve -0.591869 -1.158608
Wanda  0.408622  1.098448
Jill   0.339048  0.630279
Trey  -1.210583 -0.086196

In [39]:
map_series = pd.Series(mapping)

In [40]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: str

In [44]:
people.T.groupby(map_series).count().T

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [45]:
people.groupby(len).sum()

          a         b         c         d         e
3 -1.472425  1.119081  0.771044  0.910171  1.451980
4  1.397414 -1.384228 -1.785441  0.913905  0.530898
5 -0.285464 -1.031149 -1.344409  1.161163  1.256453

In [46]:
key_list = ['one', 'one', 'one', 'two', 'two']

In [47]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -1.472425  1.119081  0.771044  0.910171  1.451980
4 two -0.161011 -1.266772 -1.109067 -0.101516  0.192271
5 one -1.065126 -1.031149 -1.344409  0.408622  0.318786

In [48]:
columns = pd.MultiIndex.from_arrays([['US', 'US', 'US', 'JP', 'JP'],
                                     [1, 2, 5, 1, 3]],
                                     names=['cty', 'tenor'])

In [49]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)

In [50]:
hier_df

cty          US                            JP
tenor         1         2         5         1         3
0      1.860672 -0.810059  0.129834  0.318404  4.548909
1     -1.470481 -0.481693  3.186973  0.676888 -0.556795
2      0.709480 -0.043705 -0.506362 -0.792033 -0.527955
3     -0.348844 -1.064304 -0.254612  0.336219 -0.538089

In [51]:
hier_df.T.groupby(level='cty').count().T

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [52]:
df

  key1  key2     data1     data2
0    a     1  0.953980 -0.966058
1    a     2  1.369504  0.647200
2  NaN     1 -0.789297  0.480744
3    b     2  1.160445 -1.726905
4    b     1  0.024336  0.495262
5    a  <NA>  1.606693 -0.409158
6  NaN     1  0.022242 -0.186802

In [53]:
grouped = df.groupby('key1')

In [54]:
grouped['data1'].nsmallest(2)

key1
a     0    0.953980
      1    1.369504
b     4    0.024336
      3    1.160445
Name: data1, dtype: float64

In [55]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [56]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  0.652713  1.613258
b        1  1.136109  2.222167

In [57]:
grouped

In [58]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  1.310059  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0  0.592390  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     1.488099  1.606693   3.0 -0.242672  0.819414 -0.966058 -0.687608
b     0.876417  1.160445   2.0 -0.615822  1.571309 -1.726905 -1.171363


           50%       75%       max
key1
a    -0.409158  0.119021  0.647200
b    -0.615822 -0.060280  0.495262

[2 rows x 24 columns]

In [59]:
tips = pd.read_csv('../examples/tips.csv')

In [60]:
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [61]:
tips['tip_pct'] = tips['tip'] / tips['total_bill']

In [62]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [63]:
grouped = tips.groupby(['day',  'smoker'])

In [64]:
grouped_pct = grouped['tip_pct']

In [65]:
grouped_pct.agg('mean')

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [66]:
grouped_pct.agg(['mean', 'std', peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [67]:
grouped_pct.agg([('average', 'mean'), ('stdev', np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.024355
     Yes     0.174783  0.049553
Sat  No      0.158048  0.039323
     Yes     0.147906  0.060640
Sun  No      0.160113  0.041974
     Yes     0.187250  0.150023
Thur No      0.160298  0.038341
     Yes     0.163863  0.038213

In [68]:
functions = ['count', 'mean', 'max']

In [69]:
result = grouped[['tip_pct', 'total_bill']].agg(functions)

In [70]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [71]:
result['tip_pct']

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [72]:
ftuples = [('Average', 'mean'), ('Variance', np.var)]

In [73]:
grouped[['tip_pct', 'total_bill']].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000593  18.420000   19.197250
     Yes     0.174783  0.002456  16.813333   77.058276
Sat  No      0.158048  0.001546  19.661778   78.133210
     Yes     0.147906  0.003677  21.276667   98.973546
Sun  No      0.160113  0.001762  20.506667   64.940331
     Yes     0.187250  0.022507  24.120000  103.306779
Thur No      0.160298  0.001470  17.113111   58.300079
     Yes     0.163863  0.001460  19.190588   65.702135

In [74]:
grouped.agg({'tip' : np.max, 'size' : 'sum'})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [76]:
grouped.agg({'tip_pct' : ['min', 'max', 'mean', 'std'],
             'size' : 'sum'})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [78]:
tips.groupby(['day', 'smoker'], as_index=False).mean(numeric_only=True)

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863