In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'key1' : ['a', 'a', None, 'b', 'b', 'a', None],
                   'key2' : pd.Series([1, 2, 1, 2, 1, None, 1], dtype='Int64'),
                    'data1' : np.random.standard_normal(7),
                    'data2' : np.random.standard_normal(7)})

In [3]:
df

  key1  key2     data1     data2
0    a     1  0.197102 -0.818050
1    a     2 -2.009643 -2.306571
2  NaN     1 -1.037441  0.350260
3    b     2 -0.149625 -1.370756
4    b     1 -0.357013  0.212867
5    a  <NA>  0.267113 -0.488856
6  NaN     1 -1.138541 -1.908775

In [4]:
grouped = df['data1'].groupby(df['key1'])

In [5]:
grouped

In [6]:
grouped.mean()

key1
a   -0.515143
b   -0.253319
Name: data1, dtype: float64

In [7]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()

In [8]:
means

key1  key2
a     1       0.197102
      2      -2.009643
b     1      -0.357013
      2      -0.149625
Name: data1, dtype: float64

In [10]:
means.unstack()

key2         1         2
key1
a     0.197102 -2.009643
b    -0.357013 -0.149625

In [11]:
states = np.array(['OH', 'CA', 'CA', 'OH', 'OH', 'CA', 'OH'])

In [12]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [13]:
df['data1'].groupby([states, years]).mean()

CA  2005   -0.871265
    2006   -1.037441
OH  2005    0.023738
    2006   -0.747777
Name: data1, dtype: float64

In [14]:
df.groupby('key1').mean()

      key2     data1     data2
key1
a      1.5 -0.515143 -1.204493
b      1.5 -0.253319 -0.578945

In [16]:
df.groupby('key2').mean(numeric_only=True)

         data1     data2
key2
1    -0.583973 -0.540925
2    -1.079634 -1.838664

In [17]:
df.groupby(['key1', 'key2']).mean()

              data1     data2
key1 key2
a    1     0.197102 -0.818050
     2    -2.009643 -2.306571
b    1    -0.357013  0.212867
     2    -0.149625 -1.370756

In [18]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [19]:
df.groupby('key1', dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [20]:
df.groupby(['key1', 'key2'], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [21]:
df.groupby('key1').count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [22]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  0.197102 -0.818050
1    a     2 -2.009643 -2.306571
5    a  <NA>  0.267113 -0.488856
b
  key1  key2     data1     data2
3    b     2 -0.149625 -1.370756
4    b     1 -0.357013  0.212867

In [23]:
for (k1, k2), group in df.groupby(['key1', 'key2']):
    print((k1, k2))
    print(group)

('a', 1)
  key1  key2     data1    data2
0    a     1  0.197102 -0.81805
('a', 2)
  key1  key2     data1     data2
1    a     2 -2.009643 -2.306571
('b', 1)
  key1  key2     data1     data2
4    b     1 -0.357013  0.212867
('b', 2)
  key1  key2     data1     data2
3    b     2 -0.149625 -1.370756

In [24]:
pieces = {name: group for name, group in df.groupby('key1')}

In [25]:
pieces['b']

  key1  key2     data1     data2
3    b     2 -0.149625 -1.370756
4    b     1 -0.357013  0.212867

In [34]:
mapping = {'key1': 'key', 'key2': 'key',
           'data1': 'data', 'data2': 'data'}

grouped = df.T.groupby(mapping)

In [36]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values.T)

data
      data1     data2
0  0.197102  -0.81805
1 -2.009643 -2.306571
2 -1.037441   0.35026
3 -0.149625 -1.370756
4 -0.357013  0.212867
5  0.267113 -0.488856
6 -1.138541 -1.908775
key
  key1  key2
0    a     1
1    a     2
2  NaN     1
3    b     2
4    b     1
5    a  <NA>
6  NaN     1