In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'key1' : ['a', 'a', None, 'b', 'b', 'a', None],
                   'key2' : pd.Series([1, 2, 1, 2, 1, None, 1], dtype='Int64'),
                    'data1' : np.random.standard_normal(7),
                    'data2' : np.random.standard_normal(7)})

In [4]:
df

  key1  key2     data1     data2
0    a     1  1.421636  0.015234
1    a     2  1.793022  0.564999
2  NaN     1  2.406286  0.686623
3    b     2 -0.705798 -1.195768
4    b     1  0.838985 -1.694278
5    a  <NA> -0.837942  1.002763
6  NaN     1 -0.457860  1.566940

In [5]:
grouped = df['data1'].groupby(df['key1'])

In [6]:
grouped

In [7]:
grouped.mean()

key1
a    0.792238
b    0.066593
Name: data1, dtype: float64

In [8]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()

In [9]:
means

key1  key2
a     1       1.421636
      2       1.793022
b     1       0.838985
      2      -0.705798
Name: data1, dtype: float64

In [10]:
means.unstack()

key2         1         2
key1
a     1.421636  1.793022
b     0.838985 -0.705798

In [11]:
states = np.array(['OH', 'CA', 'CA', 'OH', 'OH', 'CA', 'OH'])

In [12]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [13]:
df['data1'].groupby([states, years]).mean()

CA  2005    0.477540
    2006    2.406286
OH  2005    0.357919
    2006    0.190562
Name: data1, dtype: float64

In [14]:
df.groupby('key1').mean()

      key2     data1     data2
key1
a      1.5  0.792238  0.527665
b      1.5  0.066593 -1.445023

In [15]:
df.groupby('key2').mean(numeric_only=True)

         data1     data2
key2
1     1.052261  0.143630
2     0.543612 -0.315385

In [16]:
df.groupby(['key1', 'key2']).mean()

              data1     data2
key1 key2
a    1     1.421636  0.015234
     2     1.793022  0.564999
b    1     0.838985 -1.694278
     2    -0.705798 -1.195768

In [17]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [18]:
df.groupby('key1', dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [19]:
df.groupby(['key1', 'key2'], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [20]:
df.groupby('key1').count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [21]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  1.421636  0.015234
1    a     2  1.793022  0.564999
5    a  <NA> -0.837942  1.002763
b
  key1  key2     data1     data2
3    b     2 -0.705798 -1.195768
4    b     1  0.838985 -1.694278

In [22]:
for (k1, k2), group in df.groupby(['key1', 'key2']):
    print((k1, k2))
    print(group)

('a', 1)
  key1  key2     data1     data2
0    a     1  1.421636  0.015234
('a', 2)
  key1  key2     data1     data2
1    a     2  1.793022  0.564999
('b', 1)
  key1  key2     data1     data2
4    b     1  0.838985 -1.694278
('b', 2)
  key1  key2     data1     data2
3    b     2 -0.705798 -1.195768

In [23]:
pieces = {name: group for name, group in df.groupby('key1')}

In [24]:
pieces['b']

  key1  key2     data1     data2
3    b     2 -0.705798 -1.195768
4    b     1  0.838985 -1.694278

In [25]:
mapping = {'key1': 'key', 'key2': 'key',
           'data1': 'data', 'data2': 'data'}

grouped = df.T.groupby(mapping)

In [26]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values.T)

data
      data1     data2
0  1.421636  0.015234
1  1.793022  0.564999
2  2.406286  0.686623
3 -0.705798 -1.195768
4  0.838985 -1.694278
5 -0.837942  1.002763
6  -0.45786   1.56694
key
  key1  key2
0    a     1
1    a     2
2  NaN     1
3    b     2
4    b     1
5    a  <NA>
6  NaN     1

In [27]:
df.groupby(['key1',  'key2'])[['data2']].mean()

              data2
key1 key2
a    1     0.015234
     2     0.564999
b    1    -1.694278
     2    -1.195768

In [28]:
s_grouped = df.groupby(['key1','key2'])['data2']

In [29]:
s_grouped

In [30]:
s_grouped.mean()

key1  key2
a     1       0.015234
      2       0.564999
b     1      -1.694278
      2      -1.195768
Name: data2, dtype: float64

In [31]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wanda', 'Jill', 'Trey'])

In [32]:
people.iloc[2:3, [1, 2]] = np.nan

In [33]:
people

              a         b         c         d         e
Joe   -0.780900 -0.577394  0.311385  0.421307  2.008659
Steve -0.620084  0.870711  0.327681 -1.415419  1.994403
Wanda -0.410860       NaN       NaN  0.599310 -4.348780
Jill   0.125198 -0.089981  0.200673 -0.378176  1.330800
Trey  -0.985636  0.247284  0.615448 -1.119820 -0.954932

In [34]:
mapping = {'a': 'red', 'b': 'red', 'c': 'blue',
           'd': 'blue', 'e': 'red', 'f': 'orange'}

In [35]:
by_column = people.T.groupby(mapping)

In [36]:
by_column.sum().T

           blue       red
Joe    0.732692  0.650365
Steve -1.087738  2.245030
Wanda  0.599310 -4.759640
Jill  -0.177503  1.366016
Trey  -0.504372 -1.693285

In [37]:
map_series = pd.Series(mapping)

In [38]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: str

In [39]:
people.T.groupby(map_series).count().T

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [40]:
people.groupby(len).sum()

          a         b         c         d         e
3 -0.780900 -0.577394  0.311385  0.421307  2.008659
4 -0.860439  0.157303  0.816121 -1.497997  0.375867
5 -1.030943  0.870711  0.327681 -0.816109 -2.354378

In [41]:
key_list = ['one', 'one', 'one', 'two', 'two']

In [42]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -0.780900 -0.577394  0.311385  0.421307  2.008659
4 two -0.985636 -0.089981  0.200673 -1.119820 -0.954932
5 one -0.620084  0.870711  0.327681 -1.415419 -4.348780

In [43]:
columns = pd.MultiIndex.from_arrays([['US', 'US', 'US', 'JP', 'JP'],
                                     [1, 2, 5, 1, 3]],
                                     names=['cty', 'tenor'])

In [44]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)

In [45]:
hier_df

cty          US                            JP
tenor         1         2         5         1         3
0     -1.642583 -1.967048 -2.599823 -0.400107  0.419892
1     -2.060206 -0.317523  0.991343  1.236484 -1.122746
2     -0.589870 -0.327156 -0.215265 -2.277936 -0.277067
3      0.728725 -0.075951  0.396041  0.909450 -1.023952

In [46]:
hier_df.T.groupby(level='cty').count().T

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [47]:
df

  key1  key2     data1     data2
0    a     1  1.421636  0.015234
1    a     2  1.793022  0.564999
2  NaN     1  2.406286  0.686623
3    b     2 -0.705798 -1.195768
4    b     1  0.838985 -1.694278
5    a  <NA> -0.837942  1.002763
6  NaN     1 -0.457860  1.566940

In [48]:
grouped = df.groupby('key1')

In [49]:
grouped['data1'].nsmallest(2)

key1
a     5   -0.837942
      0    1.421636
b     3   -0.705798
      4    0.838985
Name: data1, dtype: float64

In [50]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [51]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  2.630964  0.987528
b        1  1.544783  0.498509

In [52]:
grouped

In [53]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  0.792238  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0  0.066593  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     1.607329  1.793022   3.0  0.527665  0.494822  0.015234  0.290117
b     0.452789  0.838985   2.0 -1.445023  0.352499 -1.694278 -1.569650


           50%       75%       max
key1
a     0.564999  0.783881  1.002763
b    -1.445023 -1.320396 -1.195768

[2 rows x 24 columns]

In [54]:
tips = pd.read_csv('../examples/tips.csv')

In [55]:
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [56]:
tips['tip_pct'] = tips['tip'] / tips['total_bill']

In [57]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [58]:
grouped = tips.groupby(['day',  'smoker'])

In [59]:
grouped_pct = grouped['tip_pct']

In [60]:
grouped_pct.agg('mean')

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [61]:
grouped_pct.agg(['mean', 'std', peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [62]:
grouped_pct.agg([('average', 'mean'), ('stdev', np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.024355
     Yes     0.174783  0.049553
Sat  No      0.158048  0.039323
     Yes     0.147906  0.060640
Sun  No      0.160113  0.041974
     Yes     0.187250  0.150023
Thur No      0.160298  0.038341
     Yes     0.163863  0.038213

In [63]:
functions = ['count', 'mean', 'max']

In [64]:
result = grouped[['tip_pct', 'total_bill']].agg(functions)

In [65]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [66]:
result['tip_pct']

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [67]:
ftuples = [('Average', 'mean'), ('Variance', np.var)]

In [68]:
grouped[['tip_pct', 'total_bill']].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000593  18.420000   19.197250
     Yes     0.174783  0.002456  16.813333   77.058276
Sat  No      0.158048  0.001546  19.661778   78.133210
     Yes     0.147906  0.003677  21.276667   98.973546
Sun  No      0.160113  0.001762  20.506667   64.940331
     Yes     0.187250  0.022507  24.120000  103.306779
Thur No      0.160298  0.001470  17.113111   58.300079
     Yes     0.163863  0.001460  19.190588   65.702135

In [69]:
grouped.agg({'tip' : np.max, 'size' : 'sum'})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [70]:
grouped.agg({'tip_pct' : ['min', 'max', 'mean', 'std'],
             'size' : 'sum'})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [71]:
tips.groupby(['day', 'smoker'], as_index=False).mean(numeric_only=True)

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [72]:
def top(df, n=5, column='tip_pct'):
    return df.sort_values(column, ascending=False)[:n]

In [73]:
top(tips, n=6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [74]:
tips.groupby('smoker').apply(top)

            total_bill   tip   day    time  size   tip_pct
smoker
No     232       11.61  3.39   Sat  Dinner     2  0.291990
       149        7.51  2.00  Thur   Lunch     2  0.266312
       51        10.29  2.60   Sun  Dinner     2  0.252672
       185       20.69  5.00   Sun  Dinner     5  0.241663
       88        24.71  5.85  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15   Sun  Dinner     2  0.710345
       178        9.60  4.00   Sun  Dinner     2  0.416667
       67         3.07  1.00   Sat  Dinner     1  0.325733
       183       23.17  6.50   Sun  Dinner     4  0.280535
       109       14.31  4.00   Sat  Dinner     2  0.279525

In [75]:
tips.groupby(['smoker', 'day']).apply(top, n=1, column='total_bill')

                 total_bill    tip    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25  Dinner     2  0.142857
       Sat  212       48.33   9.00  Dinner     4  0.186220
       Sun  156       48.17   5.00  Dinner     6  0.103799
       Thur 142       41.19   5.00   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73  Dinner     4  0.117750
       Sat  170       50.81  10.00  Dinner     3  0.196812
       Sun  182       45.35   3.50  Dinner     3  0.077178
       Thur 197       43.11   5.00   Lunch     4  0.115982

In [76]:
result = tips.groupby('smoker')['tip_pct'].describe()

In [78]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [79]:
result.unstack('smoker')

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [80]:
tips.groupby('smoker', group_keys=False).apply(top)

     total_bill   tip   day    time  size   tip_pct
232       11.61  3.39   Sat  Dinner     2  0.291990
149        7.51  2.00  Thur   Lunch     2  0.266312
51        10.29  2.60   Sun  Dinner     2  0.252672
185       20.69  5.00   Sun  Dinner     5  0.241663
88        24.71  5.85  Thur   Lunch     2  0.236746
172        7.25  5.15   Sun  Dinner     2  0.710345
178        9.60  4.00   Sun  Dinner     2  0.416667
67         3.07  1.00   Sat  Dinner     1  0.325733
183       23.17  6.50   Sun  Dinner     4  0.280535
109       14.31  4.00   Sat  Dinner     2  0.279525

In [81]:
frame = pd.DataFrame({'data1': np.random.standard_normal(1000),
                      'data2': np.random.standard_normal(1000)})

In [82]:
frame.head()

      data1     data2
0 -1.012669  0.138115
1  0.352343  0.232254
2 -1.988203 -0.628887
3  1.098450 -0.487406
4 -1.150400  1.719575

In [83]:
quartiles = pd.cut(frame['data1'], 4)

In [84]:
quartiles.head(10)

0    (-2.194, -0.561]
1     (-0.561, 1.072]
2    (-2.194, -0.561]
3      (1.072, 2.705]
4    (-2.194, -0.561]
5     (-0.561, 1.072]
6     (-0.561, 1.072]
7     (-0.561, 1.072]
8      (1.072, 2.705]
9     (-0.561, 1.072]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-3.833, -2.194] < (-2.194, -0.561] < (-0.561, 1.072] < (1.072, 2.705]]

In [85]:
def get_stats(group):
    return pd.DataFrame(
        {'min': group.min(), 'max': group.max(),
         'count': group.count(), 'mean': group.mean()}
    )

In [86]:
grouped = frame.groupby(quartiles)

In [87]:
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-3.833, -2.194] data1 -3.826604 -2.298998     15 -2.684147
                 data2 -1.164136  2.176994     15  0.341772
(-2.194, -0.561] data1 -2.192272 -0.564166    267 -1.082652
                 data2 -2.830966  3.013515    267  0.041227
(-0.561, 1.072]  data1 -0.559082  1.068827    577  0.220290
                 data2 -2.738850  3.110577    577  0.072313
(1.072, 2.705]   data1  1.073101  2.705397    141  1.551307
                 data2 -2.819173  2.285354    141  0.072866

In [88]:
grouped.agg(['min', 'max', 'count', 'mean'])

                     data1                               data2            \
                       min       max count      mean       min       max
data1
(-3.833, -2.194] -3.826604 -2.298998    15 -2.684147 -1.164136  2.176994
(-2.194, -0.561] -2.192272 -0.564166   267 -1.082652 -2.830966  3.013515
(-0.561, 1.072]  -0.559082  1.068827   577  0.220290 -2.738850  3.110577
(1.072, 2.705]    1.073101  2.705397   141  1.551307 -2.819173  2.285354


                 count      mean
data1
(-3.833, -2.194]    15  0.341772
(-2.194, -0.561]   267  0.041227
(-0.561, 1.072]    577  0.072313
(1.072, 2.705]     141  0.072866

In [89]:
quartiles_samp = pd.qcut(frame['data1'], 4, labels=False)

In [90]:
quartiles_samp.head()

0    0
1    2
2    0
3    3
4    0
Name: data1, dtype: int64

In [91]:
grouped = frame.groupby(quartiles_samp)

In [92]:
grouped.apply(get_stats)

                  min       max  count      mean
data1
0     data1 -3.826604 -0.638516    250 -1.239517
      data2 -2.830966  3.013515    250  0.066894
1     data1 -0.636982  0.021341    250 -0.292334
      data2 -2.738850  3.110577    250 -0.040056
2     data1  0.025209  0.669461    250  0.354379
      data2 -2.448745  2.732269    250  0.102907
3     data1  0.669674  2.705397    250  1.243516
      data2 -2.819173  2.876039    250  0.142787

In [93]:
s = pd.Series(np.random.standard_normal(6))

In [94]:
s[::2] = np.nan

In [95]:
s

0         NaN
1    0.021215
2         NaN
3    0.316252
4         NaN
5   -1.526973
dtype: float64

In [96]:
s.fillna(s.mean())

0   -0.396502
1    0.021215
2   -0.396502
3    0.316252
4   -0.396502
5   -1.526973
dtype: float64

In [97]:
states = ['Ohio', 'New York', 'Vermont', 'Florida',
          'Oregon', 'Nevada', 'California', 'Idaho']

In [98]:
group_key = ['East', 'East', 'East', 'East',
             'West', 'West', 'West', 'West']

In [99]:
data = pd.Series(np.random.standard_normal(8), index=states)

In [100]:
data

Ohio         -0.340210
New York     -0.664026
Vermont       0.360539
Florida      -2.299253
Oregon        0.539085
Nevada       -1.089012
California   -0.032971
Idaho        -0.518281
dtype: float64

In [101]:
data[['Vermont', 'Nevada', 'Idaho']] = np.nan

In [102]:
data

Ohio         -0.340210
New York     -0.664026
Vermont            NaN
Florida      -2.299253
Oregon        0.539085
Nevada             NaN
California   -0.032971
Idaho              NaN
dtype: float64

In [103]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [104]:
data.groupby(group_key).count()

East    3
West    2
dtype: int64

In [106]:
data.groupby(group_key).mean()

East   -1.101163
West    0.253057
dtype: float64

In [107]:
def fill_mean(group):
    return group.fillna(group.mean())

In [108]:
data.groupby(group_key).apply(fill_mean)

East  Ohio         -0.340210
      New York     -0.664026
      Vermont      -1.101163
      Florida      -2.299253
West  Oregon        0.539085
      Nevada        0.253057
      California   -0.032971
      Idaho         0.253057
dtype: float64

In [109]:
fill_values = {'East': 0.5, 'West': -1}

In [110]:
def fill_func(group):
    return group.fillna(fill_values[group.name])

In [111]:
data.groupby(group_key).apply(fill_func)

East  Ohio         -0.340210
      New York     -0.664026
      Vermont       0.500000
      Florida      -2.299253
West  Oregon        0.539085
      Nevada       -1.000000
      California   -0.032971
      Idaho        -1.000000
dtype: float64

In [113]:
# Hearts (черви), Spades (пики), Clubs (трефи), Diamonds (бубны)
suits = ['H', 'S', 'C', 'D']
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ['A'] + list(range(2, 11)) + ['J', 'K', 'Q']
cards = []
for suit in suits:
    cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index=cards)

In [114]:
deck.head(13)

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
dtype: int64

In [116]:
def draw(deck, n=5):
    return deck.sample(n)

In [117]:
draw(deck)

6H    6
9S    9
4H    4
9D    9
5C    5
dtype: int64

In [120]:
def get_suit(card):
    # последняя буква обозначает масть
    return card[-1]

In [121]:
deck.groupby(get_suit).apply(draw, n=2)

C  3C     3
   5C     5
D  KD    10
   6D     6
H  6H     6
   3H     3
S  4S     4
   JS    10
dtype: int64

In [122]:
deck.groupby(get_suit, group_keys=False).apply(draw, n=2)

6C      6
10C    10
2D      2
9D      9
5H      5
2H      2
6S      6
7S      7
dtype: int64

In [123]:
df = pd.DataFrame({'category': ['a', 'a', 'a', 'a',
                                'b', 'b', 'b', 'b'],
                                'data': np.random.standard_normal(8),
                                'weights': np.random.uniform(size=8)})

In [124]:
df

  category      data   weights
0        a -0.796746  0.834829
1        a  0.671981  0.387279
2        a -0.460357  0.477572
3        a  0.167575  0.867435
4        b  1.389457  0.244972
5        b -0.174005  0.306841
6        b -0.229542  0.836119
7        b -0.248339  0.348110

In [125]:
grouped = df.groupby('category')

In [126]:
def get_wavg(group):
    return np.average(group['data'], weights=group['weights'])

In [127]:
grouped.apply(get_wavg)

category
a   -0.186745
b    0.004961
dtype: float64

In [130]:
close_px = pd.read_csv('../examples/stock_px.csv', parse_dates=True,
                       index_col=0)

In [131]:
close_px.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2214 non-null   float64
 1   MSFT    2214 non-null   float64
 2   XOM     2214 non-null   float64
 3   SPX     2214 non-null   float64
dtypes: float64(4)
memory usage: 86.5 KB

In [132]:
close_px.tail(4)

              AAPL   MSFT    XOM      SPX
2011-10-11  400.29  27.00  76.27  1195.54
2011-10-12  402.19  26.96  77.16  1207.25
2011-10-13  408.43  27.18  76.37  1203.66
2011-10-14  422.00  27.27  78.11  1224.58

In [133]:
def spx_corr(group):
    return group.corrwith(group['SPX'])

In [134]:
rets = close_px.pct_change().dropna()

In [135]:
def get_year(x):
    return x.year

In [137]:
by_year = rets.groupby(get_year)

In [138]:
by_year.apply(spx_corr)

          AAPL      MSFT       XOM  SPX
2003  0.541124  0.745174  0.661265  1.0
2004  0.374283  0.588531  0.557742  1.0
2005  0.467540  0.562374  0.631010  1.0
2006  0.428267  0.406126  0.518514  1.0
2007  0.508118  0.658770  0.786264  1.0
2008  0.681434  0.804626  0.828303  1.0
2009  0.707103  0.654902  0.797921  1.0
2010  0.710105  0.730118  0.839057  1.0
2011  0.691931  0.800996  0.859975  1.0

In [139]:
def corr_aapl_msft(group):
    return group['AAPL'].corr(group['MSFT'])

In [140]:
by_year.apply(corr_aapl_msft)

2003    0.480868
2004    0.259024
2005    0.300093
2006    0.161735
2007    0.417738
2008    0.611901
2009    0.432738
2010    0.571946
2011    0.581987
dtype: float64

In [ ]:
%pip install statsmodels

In [147]:
import statsmodels.api as sm
def regress(data, yvar=None, xvars=None):
    Y = data[yvar]
    X = data[xvars]
    X['intercept'] = 1
    result = sm.OLS(Y, X).fit()
    return result.params

In [148]:
by_year.apply(regress, yvar='AAPL', xvars=['SPX'])

           SPX  intercept
2003  1.195406   0.000710
2004  1.363463   0.004201
2005  1.766415   0.003246
2006  1.645496   0.000080
2007  1.198761   0.003438
2008  0.968016  -0.001110
2009  0.879103   0.002954
2010  1.052608   0.001261
2011  0.806605   0.001514

In [149]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                   'value': np.arange(12.)})

In [150]:
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [151]:
g = df.groupby('key')['value']

In [152]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [153]:
def get_mean(group):
    return group.mean()

In [154]:
g.transform(get_mean)

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [155]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [156]:
def times_two(group):
    return group * 2

In [157]:
g.transform(times_two)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [158]:
def get_ranks(group):
    return group.rank(ascending=False)

In [159]:
g.transform(get_ranks)

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [161]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [162]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [163]:
g.apply(normalize)

key
a    0    -1.161895
     3    -0.387298
     6     0.387298
     9     1.161895
b    1    -1.161895
     4    -0.387298
     7     0.387298
     10    1.161895
c    2    -1.161895
     5    -0.387298
     8     0.387298
     11    1.161895
Name: value, dtype: float64

In [164]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [165]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')

In [166]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [167]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [169]:
tips.pivot_table(index=['day', 'smoker'], numeric_only=True)

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [171]:
tips.pivot_table(index=['time','day'], columns='smoker',
                values=['tip_pct', 'size'])

                 size             tip_pct
smoker             No       Yes        No       Yes
time   day
Dinner Fri   2.000000  2.222222  0.139622  0.165347
       Sat   2.555556  2.476190  0.158048  0.147906
       Sun   2.929825  2.578947  0.160113  0.187250
       Thur  2.000000       NaN  0.159744       NaN
Lunch  Fri   3.000000  1.833333  0.187735  0.188937
       Thur  2.500000  2.352941  0.160311  0.163863

In [172]:
tips.pivot_table(index=['time', 'day'], columns='smoker',
                 values=['tip_pct', 'size'], margins=True)

                 size                       tip_pct
smoker             No       Yes       All        No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667  0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241  0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105  0.160113  0.187250  0.166897
       Thur  2.000000       NaN  2.000000  0.159744       NaN  0.159744
Lunch  Fri   3.000000  1.833333  2.000000  0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016  0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672  0.159328  0.163196  0.160803

In [173]:
tips.pivot_table(index=['time', 'smoker'], columns='day',
                 values='tip_pct', aggfunc=len, margins=True)

day             Fri   Sat   Sun  Thur  All
time   smoker
Dinner No       3.0  45.0  57.0   1.0  106
       Yes      9.0  42.0  19.0   NaN   70
Lunch  No       1.0   NaN   NaN  44.0   45
       Yes      6.0   NaN   NaN  17.0   23
All            19.0  87.0  76.0  62.0  244

In [174]:
tips.pivot_table(index=['time', 'size', 'smoker'], columns='day',
                 values='tip_pct', fill_value=0)

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No      0.000000  0.137931  0.000000  0.000000
            Yes     0.000000  0.325733  0.000000  0.000000
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893  0.000000
       3    No      0.000000  0.154661  0.152663  0.000000
            Yes     0.000000  0.144995  0.152660  0.000000
       4    No      0.000000  0.150096  0.148143  0.000000
            Yes     0.117750  0.124515  0.193370  0.000000
       5    No      0.000000  0.000000  0.206928  0.000000
            Yes     0.000000  0.106572  0.065660  0.000000
       6    No      0.000000  0.000000  0.103799  0.000000
Lunch  1    No      0.000000  0.000000  0.000000  0.181728
            Yes     0.223776  0.000000  0.000000  0.000000
       2    No      0.000000  0.000000  0.000000  0.166005
            Yes     0.181969  0.000000  0.000000  0.158843
       3    No      0.187735  0.000000  0.000000  0.084246
            Yes     0.000000  0.000000  0.000000  0.204952
       4    No      0.000000  0.000000  0.000000  0.138919
            Yes     0.000000  0.000000  0.000000  0.155410
       5    No      0.000000  0.000000  0.000000  0.121389
       6    No      0.000000  0.000000  0.000000  0.173706

In [175]:
from io import StringIO

In [176]:
data = """Sample Nationality Handedness
    1 USA Right-handed
    2 Japan Left-handed
    3 USA Right-handed
    4 Japan Right-handed
    5 Japan Left-handed
    6 Japan Right-handed
    7 USA Right-handed
    8 USA Left-handed
    9 Japan Right-handed
    10 USA Right-handed"""

In [ ]:
data = pd.read_table(StringIO(data), sep='\s+')

In [178]:
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [179]:
pd.crosstab(data['Nationality'], data['Handedness'], margins=True)

Handedness   Left-handed  Right-handed  All
Nationality
Japan                  2             3    5
USA                    1             4    5
All                    3             7   10

In [180]:
pd.crosstab([tips['time'], tips['day']], tips['smoker'], margins=True)

smoker        No  Yes  All
time   day
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244