In [1]:
%pip install pandas
%pip install numpy

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.5.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [8]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [9]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [10]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [11]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [17]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4] = np.nan

In [21]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [24]:
df.iloc[:4, 1] = np.nan

In [25]:
df.iloc[:2, 2] = np.nan

In [26]:
df

          0         1         2
0  0.869474       NaN       NaN
1  1.505949       NaN       NaN
2  0.394116       NaN -0.208928
3  1.325197       NaN  1.885672
4  1.134140  0.718775  0.290391
5  1.946938 -1.217105  0.861257
6 -0.210048  0.174519 -0.489095

In [27]:
df.dropna()

          0         1         2
4  1.134140  0.718775  0.290391
5  1.946938 -1.217105  0.861257
6 -0.210048  0.174519 -0.489095

In [28]:
df.dropna(thresh=2)

          0         1         2
2  0.394116       NaN -0.208928
3  1.325197       NaN  1.885672
4  1.134140  0.718775  0.290391
5  1.946938 -1.217105  0.861257
6 -0.210048  0.174519 -0.489095

In [29]:
df.fillna(0)

          0         1         2
0  0.869474  0.000000  0.000000
1  1.505949  0.000000  0.000000
2  0.394116  0.000000 -0.208928
3  1.325197  0.000000  1.885672
4  1.134140  0.718775  0.290391
5  1.946938 -1.217105  0.861257
6 -0.210048  0.174519 -0.489095

In [30]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.869474  0.500000  0.000000
1  1.505949  0.500000  0.000000
2  0.394116  0.500000 -0.208928
3  1.325197  0.500000  1.885672
4  1.134140  0.718775  0.290391
5  1.946938 -1.217105  0.861257
6 -0.210048  0.174519 -0.489095

In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [32]:
df.iloc[2:, 1] = np.nan

In [33]:
df.iloc[4:, 2] = np.nan

In [34]:
df

          0         1         2
0  1.010104  0.701211  0.872734
1  0.015454 -0.428248 -0.548710
2  1.260917       NaN -0.742558
3  0.168459       NaN  0.968934
4  0.838803       NaN       NaN
5 -1.798664       NaN       NaN

In [38]:
df.ffill()

          0         1         2
0  1.010104  0.701211  0.872734
1  0.015454 -0.428248 -0.548710
2  1.260917 -0.428248 -0.742558
3  0.168459 -0.428248  0.968934
4  0.838803 -0.428248  0.968934
5 -1.798664 -0.428248  0.968934

In [39]:
df.ffill(limit=2)

          0         1         2
0  1.010104  0.701211  0.872734
1  0.015454 -0.428248 -0.548710
2  1.260917 -0.428248 -0.742558
3  0.168459 -0.428248  0.968934
4  0.838803       NaN  0.968934
5 -1.798664       NaN  0.968934

In [40]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [41]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [42]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [43]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [44]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [45]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [46]:
data["v1"] = range(7)

In [47]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [48]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [51]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [61]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [62]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [63]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [64]:
data["animal"] = data["food"].map(meat_to_animal)

In [65]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [66]:
def get_animal(x):
    return meat_to_animal[x]

In [67]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

In [68]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [69]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [70]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [71]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [72]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [73]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [74]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [75]:
def transform(x):
    return x[:4].upper()

In [76]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [77]:
data.index = data.index.map(transform)

In [78]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [80]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [81]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11