In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.Series(np.random.uniform(size=9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 3, 1, 2, 2, 3]])

In [3]:
data

a  1    0.029003
   2    0.046473
   3    0.257205
b  1    0.335563
   3    0.904550
c  1    0.830143
   2    0.748669
d  2    0.611248
   3    0.799378
dtype: float64

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [5]:
data["b"]

1    0.335563
3    0.904550
dtype: float64

In [6]:
data['b': 'c']

b  1    0.335563
   3    0.904550
c  1    0.830143
   2    0.748669
dtype: float64

In [7]:
data.loc[['b', 'd']]

b  1    0.335563
   3    0.904550
d  2    0.611248
   3    0.799378
dtype: float64

In [8]:
data.loc[:, 2]

a    0.046473
c    0.748669
d    0.611248
dtype: float64

In [9]:
data.unstack()

          1         2         3
a  0.029003  0.046473  0.257205
b  0.335563       NaN  0.904550
c  0.830143  0.748669       NaN
d       NaN  0.611248  0.799378

In [10]:
data.unstack().stack()

a  1    0.029003
   2    0.046473
   3    0.257205
b  1    0.335563
   2         NaN
   3    0.904550
c  1    0.830143
   2    0.748669
   3         NaN
d  1         NaN
   2    0.611248
   3    0.799378
dtype: float64

In [11]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                    columns=[['Ohio', 'Ohio', 'Colorado'],
                            ['Green', 'Red', 'Green']])

In [12]:
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [13]:
frame.index.names = ['key1', 'key2']

In [14]:
frame.columns.names = ['state', 'color']

In [15]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [16]:
frame.index.nlevels

2

In [17]:
frame['Ohio']

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [18]:
pd.MultiIndex.from_arrays([['Ohio', 'Ohio', 'Colorado'],
                           ['Green', 'Red', 'Green']],
                           names=['state', 'color'])

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

In [19]:
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [20]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [21]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [22]:
frame.groupby(level='key2').sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [23]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two',
                            'two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]})

In [24]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [25]:
frame2 = frame.set_index(['c', 'd'])

In [26]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [27]:
frame.set_index(['c', 'd'], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [28]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [29]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': pd.Series(range(7), dtype='Int64')})

In [30]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': pd.Series(range(3), dtype='Int64')})

In [31]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [32]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [33]:
pd.merge(df1, df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [34]:
pd.merge(df1, df2, on='key')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [35]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': pd.Series(range(7), dtype='Int64')})

In [36]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': pd.Series(range(3), dtype="Int64")})

In [37]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [38]:
pd.merge(df1, df2, how='outer')

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [39]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='outer')

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [40]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                    'data1': pd.Series(range(6), dtype="Int64")})

In [41]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                    'data2': pd.Series(range(5), dtype='Int64')})

In [42]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [43]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [44]:
pd.merge(df1, df2, on='key', how='left')

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [45]:
pd.merge(df1, df2, how='inner')

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [46]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                    'key2': ['one', 'two', 'one'],
                    'lval': pd.Series([1, 2, 3], dtype='Int64')})

In [47]:
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': pd.Series([4, 5, 6, 7], dtype='Int64')})

In [50]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [51]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [49]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [52]:
pd.merge(left, right, on='key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [53]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [54]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': pd.Series(range(6), dtype='Int64')})

In [55]:
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [56]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [57]:
right1

   group_val
a        3.5
b        7.0

In [58]:
pd.merge(left1, right1, left_on='key', right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [59]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [60]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio',
                               'Nevada', 'Nevada'],
                    'key2': [2000, 2001, 2002, 2001, 2002],
                    'data': pd.Series(range(5), dtype='Int64')})

In [61]:
righth_index = pd.MultiIndex.from_arrays(
    [
        ['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
        [2001, 2000, 2000, 2000,  2001, 2002]
    ]
)

In [64]:
righth = pd.DataFrame({'event1': pd.Series([0, 2, 4, 6, 8, 10], dtype='Int64',
                                           index=righth_index),
                       'event2': pd.Series([1, 3, 5, 7, 9, 11], dtype='Int64',
                                            index=righth_index)})

In [65]:
lefth

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [66]:
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [67]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

     key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
3  Nevada  2001     3       0       1
2    Ohio  2002     2      10      11

In [68]:
pd.merge(lefth, righth, left_on=['key1', 'key2'],
         right_index=True, how='outer')

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11

In [69]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=['a', 'c', 'e'],
                     columns=['Ohio', 'Nevada']).astype('Int64')

In [70]:
rigth2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=['b', 'c', 'd', 'e'],
                      columns=['Missouri', 'Alabama']).astype('Int64')

In [71]:
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [72]:
rigth2

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [73]:
pd.merge(left2, rigth2, how='outer', left_index=True, right_index=True)

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [75]:
left2.join(rigth2, how='outer')

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [76]:
left1.join(right1, on='key')

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [77]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=['a', 'c', 'e', 'f'],
                       columns=['New York', 'Oregon'])

In [78]:
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [79]:
left2.join([rigth2, another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [80]:
left2.join([rigth2, another], how='outer')

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
b  <NA>    <NA>         7        8       NaN     NaN
c     3       4         9       10       9.0    10.0
d  <NA>    <NA>        11       12       NaN     NaN
e     5       6        13       14      11.0    12.0
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

In [81]:
arr = np.arange(12).reshape((3, 4))

In [82]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [84]:
s1 = pd.Series([0, 1], index=['a', 'b'], dtype='Int64')

In [85]:
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'], dtype='Int64')

In [86]:
s3 = pd.Series([5, 6], index=['f', 'g'], dtype='Int64')

In [87]:
s1

a    0
b    1
dtype: Int64

In [88]:
s2

c    2
d    3
e    4
dtype: Int64

In [89]:
s3

f    5
g    6
dtype: Int64

In [90]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [91]:
pd.concat([s1, s2, s3], axis='columns')

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [92]:
s4 = pd.concat([s1, s3])

In [93]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [94]:
pd.concat([s1, s4], axis='columns')

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [95]:
pd.concat([s1, s4], axis='columns', join='inner')

   0  1
a  0  0
b  1  1

In [96]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])

In [97]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: Int64

In [98]:
result.unstack()

          a     b     f     g
one       0     1  <NA>  <NA>
two       0     1  <NA>  <NA>
three  <NA>  <NA>     5     6

In [99]:
pd.concat([s1, s2, s3], axis='columns', keys=['one', 'two', 'three'])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [101]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])

In [102]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                    columns=['three', 'four'])

In [103]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [104]:
df2

   three  four
a      5     6
c      7     8

In [105]:
pd.concat([df1, df2], axis='columns', keys=['level1', 'level2'])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [106]:
pd.concat({'level1': df1, 'level2': df2}, axis='columns')

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [107]:
pd.concat([df1, df2], axis='columns', keys=['level1', 'level2'],
          names=['upper', 'lower'])

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [108]:
df1 = pd.DataFrame(np.random.standard_normal((3, 4)),
                   columns=['a', 'b', 'c', 'd'])

In [109]:
df2 = pd.DataFrame(np.random.standard_normal((2, 3)),
                   columns=['b', 'd', 'a'])

In [110]:
df1

          a         b         c         d
0  2.698565 -0.231077 -0.043646  0.551196
1 -1.634689 -0.042001 -0.245481  1.078602
2  0.865097 -0.019388  0.801587  0.133907

In [111]:
df2

          b         d         a
0  1.631288 -1.122826  0.207499
1 -0.030639  0.853920 -0.041085

In [112]:
pd.concat([df1, df2], ignore_index=True)

          a         b         c         d
0  2.698565 -0.231077 -0.043646  0.551196
1 -1.634689 -0.042001 -0.245481  1.078602
2  0.865097 -0.019388  0.801587  0.133907
3  0.207499  1.631288       NaN -1.122826
4 -0.041085 -0.030639       NaN  0.853920